setono_sylius_bulk_edit_admin_bulk_edit_products:
    path: /bulk-edit/products
    methods: [ GET, POST ]
    controller: setono_sylius_bulk_edit.controller.action.bulk_edit_products

setono_sylius_bulk_edit_admin_bulk_add_taxons_to_products:
    path: /bulk-edit/products/taxons/add
    methods: [ GET, POST ]
    controller: setono_sylius_bulk_edit.controller.action.bulk_add_taxons_to_products
